### ISSUE TITLE
Just curious

### ISSUE THREAD

**Issue by Anjum9694** [sgcderek/dsgc-helix-scaffold#1]
Hello,
You've mentioned in the latest thing (Helical antenna scaffold set (v4)) about custom generated OpenSCAD having a chance of bad stuff happening.. Just wondering what sort of bad stuff? Because I've generated and printed a helical and wondering if it may also may be bad (btw I generated from the original script not v4)

**Comment by sgcderek** [comment]
If it printed and it looks ok then it probably is ok. The new script (and also the old one to an extent) lacks measures to prevent the scaffold from generating poorly when abnormal parameters are used, such as a very high/low frequency or weird mounting footprints. Usually this ends up just being aesthetic and can be fixed by poking the scaffold with a soldering iron but still that's something I want to prevent
